# Generated by Django 6.0.6 on 2026-06-16 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniapp', '0002_alter_register_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='pincode',
            field=models.IntegerField(),
        ),
    ]
